"""Caption generator that enriches a project caption with smart hashtags and reference URL.

Public function:
    generate_caption(title: str, caption: str, pdf_url: str) -> str

Behavior:
    - Title line (truncated with ellipsis if > 80 chars) followed by blank line
    - Original caption paragraph
    - Blank line + 'Read the full thing: <pdf_url>'
    - Blank line + space‑separated hashtags generated by Gemini LLM

Gemini call:
    Uses the same pattern as dialouge_creator.py but simplified to request only hashtags.
    If the API call fails, falls back to a deterministic small hashtag set.
"""
from __future__ import annotations
import os
import re
from typing import List
import sys
from pathlib import Path

# Ensure project root (parent of this file's directory) is on sys.path so 'settings' can be imported
_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from settings import get_settings

try:
    from google import genai
except ImportError:  # Defer import error until call time
    genai = None  # type: ignore

MAX_TITLE_LEN = 80
FALLBACK_TAGS = set([
    "#AI", "#MachineLearning", "#LLM", "#Transformer", "#Tech", "#Education"
])


def _clean_hashtags(raw: str) -> List[str]:
    # Extract tokens that look like hashtags; ensure they start with # and contain alphanumerics only afterwards
    tags = re.findall(r"#[A-Za-z0-9][A-Za-z0-9_]*", raw)
    # Deduplicate preserving order
    seen = set()
    cleaned = []
    for tag in tags:
        low = tag.lower()
        if low not in seen:
            seen.add(low)
            cleaned.append(tag)
    return cleaned[:25]  # safety cap


def _generate_hashtags_via_gemini(title: str, caption: str) -> List[str]:
    settings = get_settings()
    api_key = getattr(settings, "GEMINI_API_KEY", None)
    if not api_key:
        return FALLBACK_TAGS
    if genai is None:
        return FALLBACK_TAGS

    client = genai.Client(api_key=api_key)
    model = "gemini-2.5-pro"
    prompt = f"""
You are an assistant that outputs ONLY a space-separated list of concise, high-signal hashtags (each starting with #, no explanations) relevant to the following social media reel.
Focus on AI, transformers, large language models, and any core thematic concepts present. Prefer widely used, discoverable tags. Limit to 8-15 hashtags. No duplicates. No punctuation besides the hash.

Generate tags for content that is about: 
Document title: {title}
Description: {caption}
""".strip()
    try:
        resp = client.models.generate_content(
            model=model,
            contents=[{"role": "user", "parts": [{"text": prompt}]}],
        )
        text = getattr(resp, "text", "") or ""
        tags = _clean_hashtags(text)
        if not tags:
            return list(FALLBACK_TAGS)
        existing_lower = {t.lower() for t in tags}
        union_list = tags + [t for t in FALLBACK_TAGS if t.lower() not in existing_lower]
        return union_list
    except Exception:
        return FALLBACK_TAGS


def generate_caption(title: str, caption: str, pdf_url: str) -> str:
    tags = _generate_hashtags_via_gemini(title, caption)
    hashtags_line = " ".join(tags)

    pdf_line = f"Read the full thing: {pdf_url.strip()}" if pdf_url else ""

    parts = [
        title + ("..." if not title.endswith("...") and len(title.strip()) > len(title) else ""),
        "",
        caption.strip(),
    ]
    if pdf_line:
        parts.extend(["", pdf_line])
    if hashtags_line:
        parts.extend(["", hashtags_line])

    return "\n".join(parts) + "\n"


if __name__ == "__main__":
    demo_title = "Attention is all you need until you need Retention"
    demo_caption = (
        "Introduced the Transformer architecture. It replaced recurrent and convolutional layers with a purely "
        "attention-based mechanism, enabling unprecedented parallelization and scalability. This architectural "
        "shift was the fundamental catalyst for the modern era of large language models."
    )
    demo_pdf = "https://arxiv.org/pdf/1706.03762"
    print(generate_caption(demo_title, demo_caption, demo_pdf))
